Repository patternfly/react-component-groups, pull requests merged in 2023-11, with the labels that each got.

#72 Fixed a11y component issues.
  packages/module/src/Ansible/Ansible.tsx
  packages/module/src/Ansible/__snapshots__/Ansible.test.tsx.snap
  packages/module/src/Battery/Battery.tsx
  packages/module/src/Battery/__snapshots__/Batery.test.tsx.snap
Labels: bug

#75 fix(ansible): Updated ansible color to address issue 74.
  packages/module/src/Ansible/Ansible.tsx
Labels: bug, design

#42 DetailsPage cleanup
  packages/module/patternfly-docs/content/extensions/component-groups/examples/DetailsPage/ActionButtonsExample.tsx
  packages/module/patternfly-docs/content/extensions/component-groups/examples/DetailsPage/ActionMenuExample.tsx
  packages/module/patternfly-docs/content/extensions/component-groups/examples/DetailsPage/ActionMenuGroupedExample.tsx
  packages/module/patternfly-docs/content/extensions/component-groups/examples/DetailsPage/BreadcrumbsExample.tsx
  packages/module/patternfly-docs/content/extensions/component-groups/examples/DetailsPage/DetailsPage.md
  packages/module/patternfly-docs/content/extensions/component-groups/examples/DetailsPage/DetailsPageExample.tsx
  packages/module/patternfly-docs/content/extensions/component-groups/examples/DetailsPage/DetailsPageHeaderExample.tsx
  packages/module/patternfly-docs/content/extensions/component-groups/examples/InvalidObject/InvalidObjectExample.tsx
  packages/module/src/ActionButton/ActionButton.tsx
  packages/module/src/ActionButton/index.ts
  packages/module/src/ActionMenu/ActionMenu.test.tsx
  packages/module/src/ActionMenu/ActionMenu.tsx
  packages/module/src/ActionMenu/index.ts
  packages/module/src/DetailsPage/DetailsPage.tsx
  packages/module/src/DetailsPageHeader/DetailsPageHeader.test.tsx
  packages/module/src/DetailsPageHeader/DetailsPageHeader.tsx
  packages/module/src/DetailsPageHeader/index.ts
  packages/module/src/DetailsPageHeader/utils/ActionButton.tsx
  packages/module/src/DetailsPageHeader/utils/ActionButtons.test.tsx
  packages/module/src/DetailsPageHeader/utils/ActionButtons.tsx
  packages/module/src/DetailsPageHeader/utils/ActionMenu.tsx
  packages/module/src/DetailsPageHeader/utils/Breadcrumbs.test.tsx
  packages/module/src/DetailsPageHeader/utils/Breadcrumbs.tsx
  packages/module/src/DetailsPageHeader/utils/index.ts
  packages/module/src/HorizontalNav/HorizontalNav.test.tsx
  packages/module/src/HorizontalNav/HorizontalNav.tsx
  packages/module/src/index.ts
Labels: frontend migration, hacktoberfest-accepted
